on:
  push

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Technical test-release no. ${{ github.run_number }}
          body: |
            This release was automatically triggered by a push event. It is not intended for download. Instead, install gh-md-to-html from Pypi.
          draft: false
          prerelease: true
 .
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: phseiff/github-flavored-markdown-to-html
          event-type: push-to-pypi
